-- 코드를 입력하세요
SELECT USED_GOODS_USER.USER_ID, USED_GOODS_USER.NICKNAME, CONCAT(USED_GOODS_USER.CITY, ' ' ,USED_GOODS_USER.STREET_ADDRESS1, ' ', USED_GOODS_USER.STREET_ADDRESS2) AS '전체 주소', CONCAT(LEFT(TLNO, 3), '-',MID(TLNO,4,4), '-', RIGHT(TLNO,4)) AS '전화번호'
FROM USED_GOODS_USER JOIN USED_GOODS_BOARD ON USED_GOODS_BOARD.WRITER_ID = USED_GOODS_USER.USER_ID
GROUP BY USER_ID
HAVING COUNT(USER_ID) >= 3
ORDER BY USER_ID DESC
