-- 코드를 입력하세요
SELECT 
    USED_GOODS_USER.USER_ID, 
    USED_GOODS_USER.NICKNAME, 
    CONCAT(
        CITY,
        " ",
        USED_GOODS_USER.STREET_ADDRESS1,
        " ",
        USED_GOODS_USER.STREET_ADDRESS2) as '전체주소', 
    CONCAT(
        SUBSTRING(TLNO, 1, 3),
        "-",
        SUBSTRING(TLNO, 4, 4),
        "-",
        SUBSTRING(TLNO, 8, 4)   
    ) as '전화번호'
FROM USED_GOODS_BOARD
    JOIN USED_GOODS_USER 
        ON USED_GOODS_BOARD.WRITER_ID = USED_GOODS_USER.USER_ID
GROUP BY USED_GOODS_BOARD.WRITER_ID
HAVING COUNT(USED_GOODS_BOARD.BOARD_ID) >= 3
ORDER BY USED_GOODS_USER.USER_ID DESC