-- 코드를 입력하세요
SELECT FOOD_PRODUCT.CATEGORY, FOOD_PRODUCT.PRICE, FOOD_PRODUCT.PRODUCT_NAME
FROM FOOD_PRODUCT  
JOIN (SELECT PRODUCT_ID, MAX(PRICE) AS PRICE, CATEGORY
FROM FOOD_PRODUCT
WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
GROUP BY CATEGORY
     ) AS P
ON FOOD_PRODUCT.CATEGORY = P.CATEGORY AND FOOD_PRODUCT.PRICE = P.PRICE
ORDER BY FOOD_PRODUCT.PRICE DESC