-- 데이터 유실, 입양 간 기록 있는 데 보호소에 간 기록은 없는 동물 ID, 이름
SELECT ANIMAL_OUTS.ANIMAL_ID, ANIMAL_OUTS.NAME
FROM ANIMAL_INS
    RIGHT JOIN  ANIMAL_OUTS
        ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
WHERE ANIMAL_INS.ANIMAL_ID IS NULL
