-- 코드를 작성해주세요 물고기 종류 별 물고기 이름과 잡은 수
SELECT COUNT(*) as 'FISH_COUNT', FISH_NAME_INFO.FISH_NAME
FROM FISH_INFO
   JOIN FISH_NAME_INFO ON FISH_INFO.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE
GROUP BY FISH_NAME_INFO.FISH_NAME
ORDER BY FISH_COUNT DESC