-- 코드를 입력하세요
SELECT FOOD_PRODUCT.PRODUCT_ID, FOOD_PRODUCT.PRODUCT_NAME, SUM(FOOD_PRODUCT.PRICE * TMP.AMOUNT) AS TOTAL_SALES 
FROM FOOD_PRODUCT
JOIN (SELECT PRODUCT_ID, AMOUNT
FROM FOOD_ORDER  
WHERE PRODUCE_DATE LIKE "2022-05%") AS TMP
ON TMP.PRODUCT_ID = FOOD_PRODUCT.PRODUCT_ID
GROUP BY FOOD_PRODUCT.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, FOOD_PRODUCT.PRODUCT_ID