-- 코드를 입력하세요
select distinct(CAR_RENTAL_COMPANY_CAR.CAR_ID) as CAR_ID
from CAR_RENTAL_COMPANY_CAR 
join CAR_RENTAL_COMPANY_RENTAL_HISTORY
on CAR_RENTAL_COMPANY_CAR.CAR_ID = CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID
where START_DATE between '2022-10-01' and '2022-10-31' and CAR_TYPE like '%세단%'
order by CAR_ID desc