-- 코드를 작성해주세요 부서별 평균 연봉
SELECT HR_DEPARTMENT.DEPT_ID, DEPT_NAME_EN, ROUND(SUM(HR_EMPLOYEES.SAL) / COUNT(*), 0) as 'AVG_SAL'
FROM HR_DEPARTMENT
    JOIN HR_EMPLOYEES ON HR_DEPARTMENT.DEPT_ID = HR_EMPLOYEES.DEPT_ID
GROUP BY HR_DEPARTMENT.DEPT_ID
ORDER BY AVG_SAL DESC