-- 코드를 입력하세요
SELECT DISTINCT CAR_RENTAL_COMPANY_CAR.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR
WHERE CAR_RENTAL_COMPANY_CAR.CAR_ID IN (SELECT CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE START_DATE LIKE '2022-10%')
AND CAR_RENTAL_COMPANY_CAR.CAR_TYPE LIKE '세단'
ORDER BY CAR_RENTAL_COMPANY_CAR.CAR_ID DESC