SELECT F.CATEGORY, F.PRICE AS MAX_PRICE, F.PRODUCT_NAME
FROM FOOD_PRODUCT F
JOIN (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
    HAVING CATEGORY IN ('과자', '국', '김치', '식용유')
) AS SUBQ
ON F.CATEGORY = SUBQ.CATEGORY AND F.PRICE = SUBQ.MAX_PRICE
ORDER BY MAX_PRICE DESC;